# FILEPATHS
# ============================================================================
PBEH1_1: 
  data_dir: '/group/flchedingrp/datasets/rawdata/230424_Ethan/PB896_01_PBEH1-1_Amplicon'  # path to flow cell 1 data dir
  fastq : '/group/flchedingrp/datasets/rawdata/230424_Ethan/PB896_01_PBEH1-1_Amplicon/CCS/outputs/m64069_230413_005848.hifi_reads.fastq.gz'  # extension to fastq file


PBEH1_2:
  data_dir: '/group/flchedingrp/datasets/rawdata/230424_Ethan/PB896_02_PBEH1-2_Amplicon'
  fastq: '/group/flchedingrp/datasets/rawdata/230424_Ethan/PB896_02_PBEH1-2_Amplicon/CCS/outputs/m64069_230413_111106.hifi_reads.fastq.gz'

SAMPLE_TABLE: '../resources/PBEH-1-samples.tsv'
GENOME_DIR: '../resources/referenceDNA/'
PLASMID_ID_SEQS: '../resources/plasmidID/plasmidID.fa'
PLASMID_ID_TABLE: '../resources/plasmidID/IDTable.tsv'

# parameters of workflow
NUM_SPLITS: 500